import {
  DEMO_IDENTITIES,
  resolveDemoAsset,
  toDemoUser,
} from "@/demo/runtime.js";

function identity(key) {
  return DEMO_IDENTITIES.find((item) => item.key === key);
}

export function createDemoState() {
  const users = DEMO_IDENTITIES.map((item, index) => ({
    ...toDemoUser(item),
    isLogin: false,
    muted: false,
    frozen: false,
    createTime: `2026-07-${String(20 + index).padStart(2, "0")} 09:10:00`,
  }));
  users.push({
    id: 107,
    userName: "纸月听澜",
    userAccount: "drl_reader_tinglan",
    userEmail: "drl_reader_tinglan@darkroomlibrary.local",
    userAvatar: "",
    userRole: 2,
    role: 2,
    isCoordinatorAdmin: false,
    isLogin: false,
    muted: false,
    frozen: false,
    createTime: "2026-07-26 10:18:00",
  });

  return {
    sequence: 1000,
    categories: [
      { id: 1, name: "文学", createTime: "2026-07-20 08:00:00" },
      { id: 2, name: "历史", createTime: "2026-07-20 08:05:00" },
      { id: 3, name: "科学", createTime: "2026-07-20 08:10:00" },
      { id: 4, name: "哲学", createTime: "2026-07-20 08:15:00" },
      { id: 5, name: "艺术", createTime: "2026-07-20 08:20:00" },
    ],
    bookshelves: [
      { id: 1, name: "雾灯一架", location: "一层东侧", description: "文学与随笔" },
      { id: 2, name: "青梧二架", location: "二层南侧", description: "历史与哲学" },
      { id: 3, name: "星阑三架", location: "二层北侧", description: "科学与艺术" },
    ],
    books: [
      {
        id: 1,
        name: "暗室藏书",
        author: "岑夜录",
        category: "文学",
        publisher: "暗室藏书局",
        isbn: "9900000000001",
        description: "记录一间夜间图书馆里，书与读者彼此抵达的六个片段。",
        availableCount: 3,
        totalCount: 6,
        bookshelfId: 1,
        cover: resolveDemoAsset("demo-media/dark-room-library-cover.webp"),
        createTime: "2026-07-20 10:10:00",
        deleted: false,
      },
      {
        id: 2,
        name: "雾灯索引",
        author: "江雾衡",
        category: "历史",
        publisher: "雾桥文库",
        isbn: "9900000000002",
        description: "从散落档案中重建一座旧城阅读史的索引札记。",
        availableCount: 1,
        totalCount: 4,
        bookshelfId: 2,
        cover: "",
        createTime: "2026-07-21 11:20:00",
        deleted: false,
      },
      {
        id: 3,
        name: "归架之前",
        author: "闻归舟",
        category: "文学",
        publisher: "归架书坊",
        isbn: "9900000000003",
        description: "一本书在归架前经过的借阅、批注、等待与重逢。",
        availableCount: 0,
        totalCount: 3,
        bookshelfId: 1,
        cover: "",
        createTime: "2026-07-22 14:30:00",
        deleted: false,
      },
      {
        id: 4,
        name: "星阑采书札",
        author: "栖星社编",
        category: "科学",
        publisher: "星阑书社",
        isbn: "9900000000004",
        description: "用清单和短札解释馆藏补充、版本选择与库存判断。",
        availableCount: 2,
        totalCount: 5,
        bookshelfId: 3,
        cover: "",
        createTime: "2026-07-23 09:40:00",
        deleted: false,
      },
      {
        id: 5,
        name: "青梧守卷录",
        author: "青梧馆记",
        category: "哲学",
        publisher: "青梧文献馆",
        isbn: "9900000000005",
        description: "围绕保存、开放与秩序，讨论馆员如何守护公共阅读。",
        availableCount: 2,
        totalCount: 4,
        bookshelfId: 2,
        cover: "",
        createTime: "2026-07-24 16:10:00",
        deleted: false,
      },
      {
        id: 6,
        name: "砚灯拾页集",
        author: "砚灯读书会",
        category: "艺术",
        publisher: "砚灯小筑",
        isbn: "9900000000006",
        description: "收录读者在灯下留下的短评、页边批注与阅读路径。",
        availableCount: 1,
        totalCount: 3,
        bookshelfId: 3,
        cover: "",
        createTime: "2026-07-25 19:20:00",
        deleted: false,
      },
      {
        id: 7,
        name: "灯下山河",
        author: "闻归舟",
        category: "文学",
        publisher: "归架书坊",
        isbn: "9900000000007",
        description: "沿着夜行与归途，记录人在山河之间重新认出自己的短篇集。",
        availableCount: 3,
        totalCount: 4,
        bookshelfId: 1,
        cover: "",
        createTime: "2026-07-26 10:30:00",
        deleted: false,
      },
      {
        id: 8,
        name: "魏晋微光",
        author: "江雾衡",
        category: "历史",
        publisher: "雾桥文库",
        isbn: "9900000000008",
        description: "从人物、书信与山水中辨认魏晋时代关于自由与归隐的微光。",
        availableCount: 2,
        totalCount: 3,
        bookshelfId: 2,
        cover: "",
        createTime: "2026-07-26 11:00:00",
        deleted: false,
      },
      {
        id: 9,
        name: "山水有声",
        author: "砚灯读书会",
        category: "艺术",
        publisher: "砚灯小筑",
        isbn: "9900000000009",
        description: "谈古画、诗句与园林如何共同构成中国山水中的观看和聆听。",
        availableCount: 3,
        totalCount: 3,
        bookshelfId: 3,
        cover: "",
        createTime: "2026-07-26 11:20:00",
        deleted: false,
      },
      {
        id: 10,
        name: "自由的边界",
        author: "青梧馆记",
        category: "哲学",
        publisher: "青梧文献馆",
        isbn: "9900000000010",
        description: "从规则、责任与公共生活出发，讨论自由并非孤立无边的选择。",
        availableCount: 4,
        totalCount: 5,
        bookshelfId: 2,
        cover: "",
        createTime: "2026-07-26 12:00:00",
        deleted: false,
      },
      {
        id: 11,
        name: "星图之外",
        author: "栖星社编",
        category: "科学",
        publisher: "星阑书社",
        isbn: "9900000000011",
        description: "以观测札记解释星图、尺度与人类如何在未知面前保持好奇。",
        availableCount: 4,
        totalCount: 4,
        bookshelfId: 3,
        cover: "",
        createTime: "2026-07-26 12:20:00",
        deleted: false,
      },
      {
        id: 12,
        name: "纸页与城",
        author: "岑夜录",
        category: "历史",
        publisher: "暗室藏书局",
        isbn: "9900000000012",
        description: "从书店、图书馆与私人书架的迁移，阅读一座城市留下的纸上地层。",
        availableCount: 2,
        totalCount: 4,
        bookshelfId: 2,
        cover: "",
        createTime: "2026-07-26 12:40:00",
        deleted: false,
      },
    ],
    users,
    borrowRecords: [
      {
        id: 401,
        userId: identity("reader").id,
        userName: identity("reader").name,
        bookId: 2,
        bookName: "雾灯索引",
        bookAuthor: "江雾衡",
        borrowTime: "2026-07-23 09:00:00",
        dueDate: "2026-08-22 09:00:00",
        returnTime: null,
        status: false,
        renewCount: 0,
        fine: 0,
      },
    ],
    reservations: [
      {
        id: 501,
        userId: identity("reader").id,
        userName: identity("reader").name,
        bookId: 3,
        bookName: "归架之前",
        status: 0,
        createTime: "2026-07-25 18:20:00",
        expireTime: "2026-08-05 18:20:00",
        queuePosition: 1,
      },
    ],
    favorites: [
      { id: 551, userId: identity("reader").id, bookId: 1 },
      { id: 552, userId: identity("reader").id, bookId: 5 },
      { id: 553, userId: identity("reader").id, bookId: 6 },
    ],
    recommendationEnabled: true,
    recommendationEvents: [],
    reviews: [
      {
        id: 201,
        userId: identity("reader").id,
        userName: identity("reader").name,
        bookId: 1,
        bookName: "暗室藏书",
        rating: 5,
        content: "它把借阅写成一次有去有回的相遇，最喜欢其中关于等待归还的那一页。",
        createTime: "2026-07-24 20:18:00",
        likeCount: 12,
        liked: true,
        reported: false,
        reportCount: 0,
        status: 0,
        replies: [
          {
            id: 301,
            userId: identity("coordinator").id,
            userName: identity("coordinator").name,
            replyToUserName: identity("reader").name,
            content: "这段批注已经收入本周馆员荐读，感谢你把归还之后的感受也留下来。",
            createTime: "2026-07-25 09:30:00",
          },
        ],
      },
      {
        id: 202,
        userId: 107,
        userName: "纸月听澜",
        bookId: 2,
        bookName: "雾灯索引",
        rating: 4,
        content: "目录看似安静，实际把一座城的阅读痕迹串得很清楚，适合慢慢翻。",
        createTime: "2026-07-23 18:42:00",
        likeCount: 9,
        liked: false,
        reported: false,
        reportCount: 1,
        status: 0,
        replies: [],
      },
    ],
    reviewReports: [
      {
        id: 901,
        reviewId: 202,
        bookName: "雾灯索引",
        reviewerName: "纸月听澜",
        reporterName: identity("reader").name,
        reason: "测试审核流程的演示举报",
        status: 0,
        createTime: "2026-07-26 11:20:00",
      },
    ],
    notices: [
      {
        id: 601,
        name: "暑期开放时间调整",
        content: "周末延长开放一小时。",
        createTime: "2026-07-25 08:30:00",
      },
      {
        id: 602,
        name: "新书到馆",
        content: "本周新增文学与科学类藏书。",
        createTime: "2026-07-24 10:15:00",
      },
      {
        id: 603,
        name: "归还提醒",
        content: "请留意借阅到期时间。",
        createTime: "2026-07-23 16:40:00",
      },
    ],
    messageBoard: [
      {
        id: 651,
        userId: identity("reader").id,
        userName: identity("reader").name,
        content: "希望下一批新书可以补充一些地方史与城市记忆。",
        replyContent: "已经记录到采购建议中。",
        createTime: "2026-07-25 20:10:00",
        attachmentUrl: "",
        attachmentName: "",
      },
    ],
    procurementOrders: [
      {
        id: 701,
        bookId: 3,
        bookName: "归架之前",
        requestCount: 7,
        status: 3,
        requesterId: identity("root").id,
        requesterName: identity("root").name,
        purchaserId: identity("purchaser").id,
        purchaserName: identity("purchaser").name,
        logisticsId: identity("logistics").id,
        logisticsName: identity("logistics").name,
        logisticsStatus: 0,
        carrier: "星河承运",
        trackingNo: "DRL-20260725-0701",
        logisticsRemark: "",
        updateTime: "2026-07-25 09:18:00",
        unreadCount: 1,
        stockApplied: false,
      },
      {
        id: 702,
        bookId: 6,
        bookName: "砚灯拾页集",
        requestCount: 4,
        status: 4,
        requesterId: identity("coordinator").id,
        requesterName: identity("coordinator").name,
        purchaserId: identity("purchaser").id,
        purchaserName: identity("purchaser").name,
        logisticsId: identity("logistics").id,
        logisticsName: identity("logistics").name,
        logisticsStatus: 1,
        carrier: "青梧物流",
        trackingNo: "DRL-20260725-0702",
        logisticsRemark: "两箱图书，外包装完整。",
        updateTime: "2026-07-25 10:06:00",
        unreadCount: 0,
        stockApplied: false,
      },
    ],
    procurementMessages: [
      {
        id: 801,
        orderId: 701,
        channelType: 1,
        senderId: identity("purchaser").id,
        senderName: identity("purchaser").name,
        receiverId: identity("logistics").id,
        content: "两箱图书已交接，请按运单登记到馆时间。",
        createTime: "2026-07-25 09:30:00",
      },
    ],
    operationLogs: [
      {
        id: 951,
        operatorName: identity("coordinator").name,
        operation: "审核书评举报",
        target: "书评举报",
        detail: "处理结果=保留书评",
        createTime: "2026-07-26 14:20:00",
      },
      {
        id: 952,
        operatorName: identity("purchaser").name,
        operation: "推进采购单",
        target: "采购单 #701",
        detail: "状态更新为已发货",
        createTime: "2026-07-25 09:18:00",
      },
    ],
  };
}
